language: c
compiler: gcc
dist: bionic

script:
  - i686-w64-mingw32-gcc  -m32 src/fastm1.c include/nfc-utils.c -c -I ./include
  - i686-w64-mingw32-gcc  -m32 fastm1.o nfc-utils.o -o fastm1 -L"./lib" -lnfc
