language: c
compiler: gcc
os: windows

before_install:
  - export PATH=/C/tools/msys64/mingw32/bin:$PATH
  - ls /C/tools/msys64/mingw32/bin
  - gcc -v
  - cd build
  - cmake .. -G "MinGW Makefiles" -D CMAKE_SH="CMAKE_SH-NOTFOUND"

script:
  - mingw32-make
